{% set version = "0.8.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-d3r
  version: {{ version|replace("-", "_") }}

source:
  fn: d3r_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/d3r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/d3r/d3r_{{ version }}.tar.gz
  sha256: c7e180eb2d7e25fbebb21053e7ed64cce19c57ae891098596823c7caa3112218

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-tidyr >=0.7.0
  run:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-tidyr >=0.7.0

test:
  commands:
    - $R -e "library('d3r')"           # [not win]
    - "\"%R%\" -e \"library('d3r')\""  # [win]

about:
  home: https://github.com/timelyportfolio/d3r
  license: BSD_3_clause
  summary: Provides a suite of functions to help ease the use of 'd3.js' in R. These helpers
    include 'htmltools::htmlDependency' functions, hierarchy builders, and conversion
    tools for 'partykit', 'igraph,' 'table', and 'data.frame' R objects into the 'JSON'
    that 'd3.js' expects.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
