{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-d3r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/d3r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/d3r/d3r_{{ version }}.tar.gz
  sha256: c3f59b6551f7c19fbf6f81421d28d74f565b82cc23178dfc56dad0434017c91e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-rlang
    - r-tidyr >=0.8.3
  run:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-rlang
    - r-tidyr >=0.8.3

test:
  commands:
    - $R -e "library('d3r')"           # [not win]
    - "\"%R%\" -e \"library('d3r')\""  # [win]

about:
  home: https://github.com/timelyportfolio/d3r
  license: BSD-3-Clause
  summary: Provides a suite of functions to help ease the use of 'd3.js' in R. These helpers include 'htmltools::htmlDependency' functions, hierarchy builders, and conversion tools for 'partykit', 'igraph,' 'table', and 'data.frame' R objects into the 'JSON' that 'd3.js' expects.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: d3r
# Type: Package
# Title: 'd3.js' Utilities for R
# Version: 0.8.7
# Date: 2019-08-20
# Authors@R: c( person( "Mike", "Bostock" , role = c("aut", "cph") , comment = "d3.js library in htmlwidgets/lib, http://d3js.org" ), person( "Kent", "Russell" , role = c("aut", "cre") , comment = "R interface" , email = "kent.russell@timelyportfolio.com" ), person( "Gregor", "Aisch" , role = c("aut", "cph") , comment = "d3-jetpack creator, https://github.com/gka/d3-jetpack" ), person( "Adam", "Pearce" , role = c("aut") , comment = "core contributor to d3-jetpack" ), person( "Ben", "Ortiz" , role = c("ctb") ) )
# Maintainer: Kent Russell <kent.russell@timelyportfolio.com>
# URL: https://github.com/timelyportfolio/d3r
# BugReports: https://github.com/timelyportfolio/d3r/issues
# Description: Provides a suite of functions to help ease the use of 'd3.js' in R. These helpers include 'htmltools::htmlDependency' functions, hierarchy builders, and conversion tools for 'partykit', 'igraph,' 'table', and 'data.frame' R objects into the 'JSON' that 'd3.js' expects.
# License: BSD_3_clause + file LICENSE
# Encoding: UTF-8
# Imports: dplyr, htmltools, tidyr (>= 0.7.0)
# Suggests: httr, jsonlite, listviewer, purrr, testthat
# Enhances: igraph, partykit, rpart, treemap, V8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-21 02:31:10 UTC; kentr
# Author: Mike Bostock [aut, cph] (d3.js library in htmlwidgets/lib, http://d3js.org), Kent Russell [aut, cre] (R interface), Gregor Aisch [aut, cph] (d3-jetpack creator, https://github.com/gka/d3-jetpack), Adam Pearce [aut] (core contributor to d3-jetpack), Ben Ortiz [ctb]
# Repository: CRAN
# Date/Publication: 2019-08-21 10:51:25 UTC
