appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: RDjLIYUFQqcBwsHJMrXf4l+8LYFkqrYc6clw2IQg+M+v0333itu6WUPMMAzhSZ8yuViVsv2gMJLr0ZBUghptqCdOLPDNOKwKPefDmQIfv1jgEfk/ywC5ja5qcTIcFgKLeVs+eWRDKeXFOrYfv23oXqq/nbE3/vAo7/+TlFJGOTunCg0OaxRp/R/lhs5CpMmD2i4e+9KPkpCnc07etDrEgCBT6hAGbvjLpYSxKqOpRClwyBnZL7m36E2DhKldmMMKSPOr3Pkme6+P9CxhxSe6flY+Itno3H/RfcNehIlqLF9DFwT0gmoZtCDz2n0OytLSXguDvhPiQ43fUk130MAK9jlTx5Ao/7DehbvDBvts13viqAZ9zyHwLqW8ETrpTkf/AnYtcCVbNsH12KQHd40Q0xA2FAeCbbgwqM2jnLfuCIouIxLKdfI8uOt/l+GgPMJXopmRyK5Jox24oSdxb5lUkWE9xMpDHyCu/xpTwJGiP81GueVxmQ5oFOEZN89a/xAobkjFx8ZHNKnDsVHNVfukewz/1erVDCaYQ181dtUXJ+H1iHtFTEYoGJCi3KW9Fc0Z2VP14uWy4sdcHTAjZgxWIHXtovElXMIvddTh+QAjDCFVbZPrmY0jxW3cHSsvayCNPl5hfYtBl/OWwPaiyXdgHsMnLXK2Pipsza9htm00r9Y=}
